# Use root/example as user/password credentials
services:
  server:
    build: ./frontend/
    container_name: node
    command: node Server/app.js
    volumes:
      - ./frontend/:/SSO/code/
    ports:
      - "3000:3000"
    environment:
      IS_DOCKER: 1
  python-api:
    build: ./PythonServer/
    container_name: python
    volumes:
      - ./PythonServer/:/SSO/code/
    command: python main.py
    environment:
      IS_DOCKER: 1
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sql:/home/mysql
